### PR TITLE
Add pre-commit-hook to run ejsonkms encrypt

### PR DESCRIPTION
**Pull request by mmartinenvato**
Add `.pre-commit-hooks.yaml` configuration with a hook `run-ejsonkms-encrypt` to run `ejsonkms encrypt` on all `.ejson` files in a repository

### CODE REVIEW

**Review by viraptor — COMMENTED** [review]
I'm a bit confused about it in this repo. Isn't that something you want in the repo where you're using ejsonkms, rather than in the ejsonkms project itself? Or were you aiming for an example file here?

**Comment by mmartinenvato** [comment]
Hi @viraptor 

There are two parts required for a pre-commit hook.
The `.pre-commit-hooks.yaml` file defines that this repository has a hook/s. This config shows the actual code to be run, by the entry point. More details [here](https://pre-commit.com/#new-hooks). 

Then, in other repositories that want to use this hook you would configure an entry in your `.pre-commit-config.yaml` file like the following:

```yaml
repos:
  - repo: https://github.com/envato/ejsonkms
    hooks:
      -id: run-ejsonkms-encrypt
```

**Comment by viraptor** [comment]
Since it's a yaml file, it could use that description as a comment at the top. And maybe something in the readme as well. In general, I don't see a reason not to include it.

**Review by stergiom — COMMENTED** [review]
Don't see a reason not to add this. Consider updating the Readme with a ref to pre-commit like at https://github.com/Shopify/ejson#see-also.

Afaict, `ejsonkms encrypt` simply wraps `ejson encrypt` (I know I've used the latter at times). Might be worth suggesting use of https://github.com/Shopify/ejson/blob/master/.pre-commit-hooks.yaml too in the Readme.

**Comment by mmartinenvato** [comment]
@viraptor @stergiom thanks for the feedback - I've added documentation. I think it is still useful to have the hook in this repo as well as the standard `ejson` one, even if `ejsonkms encrypt` is just a wrapper.

**Review by viraptor — APPROVED** [review]

**Review by stergiom — APPROVED** [review]

**Pull request merged**
